type Todo {
  task: String!
  completed: Boolean!
  owner: User!
  date: String
  time: String 
}

type User {
  email: String! @unique
  todos: [Todo!] @relation
  city: String
}

type Query {
  allTodos: [Todo!]
  allTodosSortedByTime: [Todo!]! @resolver(name: "sort_by_time", paginated: true)
  allTodosSortedByDate: [Todo!]! @resolver(name: "sort_by_date", paginated: true)
}
